# Generated by Django 2.2.5 on 2019-09-14 20:42

import parentalcheck.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DangerType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Danger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('danger_level', models.CharField(choices=[('N', 'None'), ('L', 'Low'), ('M', 'Medium'), ('H', 'Hight')], default='N', max_length=1)),
                ('danger_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parentalcheck.DangerType')),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=200)),
                ('content_type', models.CharField(choices=[('S', 'Site'), ('I_A', 'Instagram Account'), ('Y_C', 'Youtube Channel'), ('F_G', 'Facebook Group'), ('F_A', 'Facebook Account'), ('T_A', 'Twitter Account'), ('R_T', 'Reddit Thread')], max_length=3)),
                ('image', models.ImageField(blank=True, null=True, upload_to=parentalcheck.models.get_image_path)),
                ('dangers', models.ManyToManyField(blank=True, to='parentalcheck.Danger')),
            ],
        ),
    ]
